METHOD_MAP = {
    "d_unan": 0,
    "d_maj": 1,
    "d_split": 2,
    "kotko": 3,
    "sub": 4,
    "unknown": 5,
    None: 6,
}

FIGHT_TYPE_MAP = {
    "main": 0,
    "title": 1,
    None: 2,
}

STANCE_MAP = {
    "Orthodox": 0,
    "Southpaw": 1,
    "Switch": 2,
    None: 3,
}

WEIGHT_CLASS_MAP = {
    "Flyweight": 0,
    "Bantamweight": 1,
    "Featherweight": 2,
    "Lightweight": 3,
    "Welterweight": 4,
    "Middleweight": 5,
    "Light Heavyweight": 6,
    "Heavyweight": 7,
    "Catch Weight": 8,
    None: 9,
}

REFEREE_MAP = {
    "Adam Martinez": 0,
    "Al Guinee": 1,
    "Al Wichgers": 2,
    "Alan Abeles": 3,
    "Anders Ohlsson": 4,
    "Andrew Glenn": 5,
    "Andy Social": 6,
    "Anthony Hamlett": 7,
    "Barry Gallant": 8,
    "Bassel Mahgoub": 9,
    "Bill Bookwalter": 10,
    "Bill Clancy": 11,
    "Bladimir Puga": 12,
    "Blake Grice": 13,
    "Bobby  Wombacher": 14,
    "Bobby Rehman": 15,
    "Brad Jardine": 16,
    "Brandon Pfannenstiel": 17,
    "Brent McKeehan": 18,
    "Brian Beauchamp": 19,
    "Bruce Allen": 20,
    "Bryan Miner": 21,
    "Camila Albuquerque": 22,
    "Chad Trukovich": 23,
    "Chip Snider": 24,
    "Chris Adams": 25,
    "Chris Hill": 26,
    "Chris Reed": 27,
    "Chris Tognoni": 28,
    "Christophe Chapuis": 29,
    "Cyril Desjardins": 30,
    "Dale Frye": 31,
    "Dan Miragliotta": 32,
    "Dan Stell": 33,
    "Daniel Movahedi": 34,
    "Dave Hagen": 35,
    "Dave Jobeun": 36,
    "Dave Seljestad": 37,
    "David Smith": 38,
    "Don Turnage": 39,
    "Donnie Jessup": 40,
    "Dwayne Bess": 41,
    "Ed Collantes": 42,
    "Eduardo Herdy": 43,
    "Elvis Bello": 44,
    "Eric McMahon": 45,
    "Eric Nevitt": 46,
    "Erick Philippeaux": 47,
    "Fernando Portella": 48,
    "Fernando Salas Navarro": 49,
    "Fernando Yamasaki": 50,
    "Frank Collazo": 51,
    "Frank Gentile": 52,
    "Frank Trigg": 53,
    "Gabe Barahona": 54,
    "Gary Copeland": 55,
    "Gary Forman": 56,
    "Gary Ritter": 57,
    "Gasper Oliver": 58,
    "George Allen": 59,
    "George Conley": 60,
    "Graham Bettes": 61,
    "Grant Waterman": 62,
    "Greg Franklin": 63,
    "Greg Kleynjans": 64,
    "Herb Dean": 65,
    "Horacio Lopez Villanueva": 66,
    "Jacob Montalvo": 67,
    "Jakub Muller": 68,
    "James Chappell": 69,
    "James Folsom": 70,
    "James Warring": 71,
    "Jason Herzog": 72,
    "Jason McCoy": 73,
    "Jason Stafin": 74,
    "Jeff Hoiby": 75,
    "Jeff Rexroad": 76,
    "Jerin Valel": 77,
    "Jerry Krysz": 78,
    "Jerry Poe": 79,
    "Jim Perdios": 80,
    "Jimmy Neely": 81,
    "Joao Claudio Soares": 82,
    "Joe Coca": 83,
    "Joe Solis": 84,
    "Joel Ojeda": 85,
    "John Cooper": 86,
    "John English": 87,
    "John Hosegood": 88,
    "John McCarthy": 89,
    "John Sharp": 90,
    "Jon Schorle": 91,
    "Jonathan Romero": 92,
    "Jorge Alonso": 93,
    "Jorge Ortiz": 94,
    "Joseph Hawes": 95,
    "Josh Rosenthal": 96,
    "Josh Stewart": 97,
    "Josh Ward": 98,
    "Julio Catarino": 99,
    "Justin Brown": 100,
    "Keith Peterson": 101,
    "Kerry Hatley": 102,
    "Kevin Dornan": 103,
    "Kevin MacDonald": 104,
    "Kevin Mulhall": 105,
    "Kevin Nix": 106,
    "Kevin Sataki": 107,
    "Kim Winslow": 108,
    "Kiselev Viacheslav": 109,
    "Kristian Hacklou": 110,
    "Kyle Cardinal": 111,
    "Larry Carter": 112,
    "Larry Downs, Jr.": 113,
    "Larry Folsom": 114,
    "Leon Roberts": 115,
    "Liam Kerrigan": 116,
    "Loic Pora": 117,
    "Luc Lefebvre": 118,
    "Lukasz Bosacki": 119,
    "Luke Boutin": 120,
    "Marc Fennell": 121,
    "Marc Goddard": 122,
    "Marc Wasem": 123,
    "Marc-Andre Cote": 124,
    "Marcio Laselva": 125,
    "Marcos Rosales": 126,
    "Mario Yamasaki": 127,
    "Mark Carter": 128,
    "Mark Craig": 129,
    "Mark Lawley": 130,
    "Mark Matheny": 131,
    "Mark Simpson": 132,
    "Mark Smith": 133,
    "Marko Gyllenland": 134,
    "Mathew  Rocca": 135,
    "Matt Wynne": 136,
    "Michael Cardoso": 137,
    "Miguel Jimenez": 138,
    "Mike Bell": 139,
    "Mike Beltran": 140,
    "Mike England": 141,
    "Mike King": 142,
    "Mike Reid": 143,
    "Mitch Cadlick": 144,
    "Nate Mann": 145,
    "Neil Hall": 146,
    "Neil Swailes": 147,
    "Nic Jones": 148,
    "Nick Berens": 149,
    "Nick Cimmarusti": 150,
    "Osiris Maia": 151,
    "Osiris de Medeiros": 152,
    "Otto Torriero": 153,
    "Patricio Carlos": 154,
    "Peter Hickmott": 155,
    "Phil Koldyk": 156,
    "Philippe Chartier": 157,
    "Piotr Michalak": 158,
    "Raul Porrata": 159,
    "Rebin Saber": 160,
    "Rich Mitchell": 161,
    "Rick McCoy": 162,
    "Ricky Parker": 163,
    "Rob Hinds": 164,
    "Rob Mooney": 165,
    "Robbie Scheureumann": 166,
    "Robert Long": 167,
    "Robert Madrigal": 168,
    "Robert Romero": 169,
    "Rulon Day": 170,
    "Ryan Brueggeman": 171,
    "Sal Ram": 172,
    "Scott Howard": 173,
    "Shawn Gregory": 174,
    "Steve Mazzagatti": 175,
    "Steve Newport": 176,
    "Steve Perceval": 177,
    "Steve Rita": 178,
    "Thomas Fan": 179,
    "Tim Mills": 180,
    "Todd Frederickson": 181,
    "Todd McGovern": 182,
    "Todd Ronald Anderson": 183,
    "Tom Johnson": 184,
    "Tom Supnet": 185,
    "Tomasz Bronder": 186,
    "Tomaz Bendy": 187,
    "Travis Metteer": 188,
    "Troy Waugh": 189,
    "Tyler Tomlinson": 190,
    "Tyrone Roberts": 191,
    "Vance Swerdan": 192,
    "Vitor Ribeiro": 193,
    "Vjacheslav Kiselev": 194,
    "Vyacheslav  Kiselev": 195,
    "Wayne Spinola": 196,
    "Wernei Cardoso": 197,
    "Wolf Menninger": 198,
    "Yves Lavigne": 199,
    "Zach Teiberis": 200,
    None: 201,
}
